apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-drac
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-drac@sha256:46ed195ce19cd7cc606e0c964bc092d50b1ecd15aa4c527c9ceaea04c2b36acc
        name: my-nodejs
        resources: {}
status: {}
